---
title: I need to make a website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: 'Handpicked website platforms for design-conscious makers and entrepreneurs.
  If it''s not great, it''s not here.

'
baseurl: ''
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
